services:
  oscbot:
    image: ghcr.io/ibuergis/oscbot:latest
    container_name: oscbot
    user: "1000:1000"
    volumes:
      - ./danser/Songs:/app/danser/Songs
      - ./danser/Skins:/app/danser/Skins
      - ./danser/Replays:/app/danser/Replays
      - ./danser/videos:/app/danser/videos
      - ./token.json:/app/oscbot/token.json
      - ./youtube_secret.json:/app/oscbot/youtube_secret.json
      - ./credentials.json:/app/danser/settings/credentials.json
    env_file:
      - .env
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
                - compute
                - video
                - graphics
