services:
  oscbot:
    image: ghcr.io/ibuergis/oscbot:${OSC_BOT_IMAGE_TAG:-latest}
    container_name: oscbot
    user: "1000:1000"
    env_file:
      - .env
    volumes:
      - ./volume/Songs:/app/danser/Songs
      - ./volume/Skins:/app/danser/Skins
      - ./volume/Replays:/app/danser/Replays
      - ./volume/videos:/app/danser/videos
      - ./token.json:/app/oscbot/token.json
      - ./youtube_secret.json:/app/oscbot/youtube_secret.json:ro
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
                - compute
                - video
